import * as React from "react";
//import Typography from "@material-ui/core/Typography";
import { Link } from "react-router-dom";

class Contact extends React.Component {
    render() {
        return (
            <>
            <p>
                Contact
            </p>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nec tincidunt praesent semper feugiat. Venenatis a condimentum vitae sapien pellentesque. At lectus urna duis convallis. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus non. Libero justo laoreet sit amet cursus. Porttitor leo a diam sollicitudin tempor id. Quis eleifend quam adipiscing vitae. Curabitur vitae nunc sed velit dignissim sodales ut. Eu tincidunt tortor aliquam nulla facilisi cras fermentum. Nulla facilisi etiam dignissim diam.

                Pulvinar mattis nunc sed blandit libero. Arcu dictum varius duis at consectetur lorem donec massa. Quis lectus nulla at volutpat. Amet risus nullam eget felis eget. Faucibus in ornare quam viverra orci sagittis eu. Pellentesque elit eget gravida cum sociis natoque. Neque ornare aenean euismod elementum. Nulla posuere sollicitudin aliquam ultrices sagittis orci a. Dui nunc mattis enim ut tellus elementum. Malesuada fames ac turpis egestas maecenas pharetra convallis. Aliquet porttitor lacus luctus accumsan tortor posuere ac. Mauris nunc congue nisi vitae suscipit tellus mauris a diam. Donec et odio pellentesque diam volutpat.

                Proin sed libero enim sed. Purus in massa tempor nec feugiat nisl pretium. Netus et malesuada fames ac turpis egestas integer eget aliquet. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam. Odio facilisis mauris sit amet massa vitae tortor. Eros in cursus turpis massa. Id diam maecenas ultricies mi. Elementum nisi quis eleifend quam adipiscing vitae proin. Tristique senectus et netus et malesuada fames ac turpis egestas. Vel quam elementum pulvinar etiam non quam lacus suspendisse faucibus. Tellus cras adipiscing enim eu turpis egestas pretium aenean pharetra. Diam donec adipiscing tristique risus nec feugiat in.

                Enim tortor at auctor urna nunc id cursus metus. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Amet commodo nulla facilisi nullam. Vulputate dignissim suspendisse in est ante in. Egestas quis ipsum suspendisse ultrices gravida dictum. Mattis enim ut tellus elementum sagittis vitae et leo duis. Accumsan tortor posuere ac ut. Nisl suscipit adipiscing bibendum est. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Varius morbi enim nunc faucibus. Morbi tincidunt ornare massa eget egestas purus viverra accumsan in. Integer feugiat scelerisque varius morbi enim. Faucibus ornare suspendisse sed nisi lacus sed viverra. Pellentesque id nibh tortor id. Pretium aenean pharetra magna ac. Odio morbi quis commodo odio. Vulputate eu scelerisque felis imperdiet proin fermentum leo vel.

                Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Gravida neque convallis a cras semper. Id diam maecenas ultricies mi. Amet porttitor eget dolor morbi non arcu. Non blandit massa enim nec dui nunc mattis enim ut. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Massa ultricies mi quis hendrerit. Elementum nibh tellus molestie nunc non. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Vel turpis nunc eget lorem dolor. Donec pretium vulputate sapien nec. Auctor neque vitae tempus quam pellentesque. Cursus sit amet dictum sit amet justo donec enim.

                Mattis rhoncus urna neque viverra justo nec ultrices. Nulla aliquet porttitor lacus luctus accumsan. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed. Facilisis mauris sit amet massa vitae tortor condimentum. Magna fringilla urna porttitor rhoncus dolor purus non enim praesent. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus. Aliquet nec ullamcorper sit amet risus nullam. Ultrices in iaculis nunc sed augue lacus viverra vitae. Lorem dolor sed viverra ipsum. Ullamcorper a lacus vestibulum sed arcu non. Morbi tristique senectus et netus et. Enim tortor at auctor urna. Non curabitur gravida arcu ac tortor dignissim. Tortor vitae purus faucibus ornare suspendisse sed. Pellentesque adipiscing commodo elit at imperdiet dui accumsan. Arcu odio ut sem nulla pharetra diam sit amet.

                Nulla facilisi nullam vehicula ipsum a arcu. Vitae et leo duis ut diam. Semper eget duis at tellus at. A pellentesque sit amet porttitor eget dolor. Augue mauris augue neque gravida in. Et molestie ac feugiat sed lectus. Nullam vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Non enim praesent elementum facilisis leo. Metus aliquam eleifend mi in.

                Dolor magna eget est lorem ipsum dolor sit amet consectetur. Orci nulla pellentesque dignissim enim sit amet venenatis urna cursus. Proin libero nunc consequat interdum. Venenatis a condimentum vitae sapien pellentesque habitant morbi tristique. Viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est. Netus et malesuada fames ac turpis egestas. In egestas erat imperdiet sed euismod. Pellentesque dignissim enim sit amet venenatis urna cursus eget nunc. Felis bibendum ut tristique et. Tristique senectus et netus et malesuada fames ac turpis. Eu sem integer vitae justo eget magna fermentum iaculis. Nibh tellus molestie nunc non blandit massa enim nec.

                Vivamus at augue eget arcu dictum varius duis at. Mi ipsum faucibus vitae aliquet nec ullamcorper. Consequat semper viverra nam libero justo. Nunc eget lorem dolor sed viverra. Consectetur libero id faucibus nisl tincidunt eget nullam non. Quam id leo in vitae. Consectetur a erat nam at lectus urna duis convallis convallis. Aliquam id diam maecenas ultricies. Diam volutpat commodo sed egestas egestas fringilla phasellus. Pharetra convallis posuere morbi leo urna. Quam id leo in vitae turpis massa sed elementum. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra orci. Suspendisse ultrices gravida dictum fusce ut placerat orci.

                Maecenas accumsan lacus vel facilisis volutpat est. Nunc lobortis mattis aliquam faucibus purus in. Enim sed faucibus turpis in eu mi bibendum neque. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus non. Tellus id interdum velit laoreet. Faucibus interdum posuere lorem ipsum. Adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Eget felis eget nunc lobortis. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium. Iaculis eu non diam phasellus. Euismod elementum nisi quis eleifend quam adipiscing vitae. Proin sagittis nisl rhoncus mattis rhoncus. Facilisis volutpat est velit egestas dui id ornare arcu odio.

                Lorem dolor sed viverra ipsum nunc aliquet. Amet aliquam id diam maecenas ultricies mi eget mauris. Ut tristique et egestas quis ipsum suspendisse ultrices. Pharetra diam sit amet nisl suscipit adipiscing bibendum est ultricies. Tellus id interdum velit laoreet id donec ultrices tincidunt. Volutpat diam ut venenatis tellus in metus vulputate eu. In ornare quam viverra orci. Fringilla urna porttitor rhoncus dolor purus non enim praesent elementum. Sit amet purus gravida quis. Curabitur gravida arcu ac tortor dignissim. In cursus turpis massa tincidunt dui ut. Ut pharetra sit amet aliquam id diam maecenas ultricies mi. Risus quis varius quam quisque id diam vel. Accumsan lacus vel facilisis volutpat est velit egestas dui id.

                Purus semper eget duis at tellus at urna. Purus non enim praesent elementum. Aliquet nec ullamcorper sit amet risus nullam. Ornare arcu dui vivamus arcu felis bibendum ut tristique et. Consequat nisl vel pretium lectus quam id leo. A erat nam at lectus urna duis convallis convallis. Sed viverra tellus in hac habitasse platea dictumst vestibulum. Egestas dui id ornare arcu odio ut sem nulla pharetra. Feugiat in fermentum posuere urna nec tincidunt praesent semper. Enim nunc faucibus a pellentesque sit amet porttitor eget. Nulla at volutpat diam ut venenatis tellus in. Condimentum lacinia quis vel eros donec. Etiam erat velit scelerisque in dictum non consectetur. Felis eget velit aliquet sagittis.
            </p>
            <Link to="/">Home</Link>
            </>
        );
    }
}

export default Contact;
